#security:
#  oauth2:
##    sso:
##      login-path: /login
spring:
  profiles:
    active: production
  session:
    store-type: redis

#spring:
#  redis:
#    host: localhost
#    password: secret
#    port: 6379